# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StellarObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('stellar_object_type', models.CharField(default=b'Quasar', max_length=50)),
                ('distance', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Stellar Object',
                'verbose_name_plural': 'Stellar Objects',
            },
        ),
    ]
