# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0002_constellation_brightest_star'),
        ('stellar_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stellarobject',
            name='constellation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='constellations.Constellation'),
        ),
    ]
