# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('galaxy_name', models.CharField(max_length=50)),
                ('galaxy_type', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(default=None)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=6)),
                ('diameter', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('number_of_stars', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('galaxy_mass', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Galaxy',
                'verbose_name_plural': 'Galaxies',
            },
        ),
    ]
