# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('constellation_name', models.CharField(max_length=50)),
                ('iau_abbr', models.CharField(max_length=20)),
                ('other_abbr', models.CharField(max_length=20)),
                ('genitive', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(blank=True, max_length=50, null=True)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('meaning', models.CharField(blank=True, max_length=50, null=True)),
                ('right_ascension', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('declination', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('number_of_stars', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('stars_with_planets', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Constellation',
                'verbose_name_plural': 'Constellations',
            },
        ),
    ]
