# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFormFailureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.TextField()),
                ('model_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('magnitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('bayer_designation', models.CharField(max_length=50)),
                ('proper_name', models.CharField(max_length=50)),
                ('distance', models.DecimalField(decimal_places=5, max_digits=8)),
                ('spectral_class', models.CharField(max_length=50)),
                ('evolution_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('star_mass', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('star_age', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('surface_temperature', models.CharField(blank=True, max_length=50, null=True)),
                ('visual_brightness', models.IntegerField(blank=True, default=None, null=True)),
                ('star_volume', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Star',
                'verbose_name_plural': 'Stars',
            },
        ),
    ]
