# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('constellation_name', models.CharField(max_length=50)),
                ('iau_abbr', models.CharField(max_length=20)),
                ('other_abbr', models.CharField(max_length=20)),
                ('genitive', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(blank=True, max_length=50, null=True)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('meaning', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Constellation',
                'verbose_name_plural': 'Constellations',
            },
        ),
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('galaxy_name', models.CharField(max_length=50)),
                ('notes', models.TextField(default=None)),
                ('distance', models.PositiveIntegerField()),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Constellation')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Galaxy',
                'verbose_name_plural': 'Galaxies',
            },
        ),
        migrations.CreateModel(
            name='ModelFormFailureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.TextField()),
                ('model_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('magnitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bayer_designation', models.CharField(max_length=50)),
                ('proper_name', models.CharField(max_length=50)),
                ('distance', models.PositiveIntegerField()),
                ('spectral_class', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Star',
                'verbose_name_plural': 'Stars',
            },
        ),
        migrations.CreateModel(
            name='StellarObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('distance', models.PositiveIntegerField()),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Constellation')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Stellar Object',
                'verbose_name_plural': 'Stellar Objects',
            },
        ),
        migrations.AddField(
            model_name='constellation',
            name='brightest_star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Star'),
        ),
    ]
