# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0001_initial'),
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='constellation_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constellations.Constellation'),
        ),
    ]
