# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constellation',
            name='brightest_star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stars.Star'),
        ),
    ]
