# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_star_constellation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='constellation_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='constellations.Constellation'),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_age',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='visual_brightness',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
