# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0005_auto_20160315_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='stellarobject',
            name='stellar_object_type',
            field=models.CharField(default='Quasar', max_length=50),
        ),
    ]
