# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0006_stellarobject_stellar_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='constellation_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stars.Constellation'),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='distance',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
