# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0007_auto_20160317_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='evolution_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
