# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0008_star_evolution_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='magnitude',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
